services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterConnector\:
    resource: '../Classes/*'

  Brotkrueml\JobRouterConnector\Utility\FileUtility:
    public: true

  Brotkrueml\JobRouterConnector\Command\GenerateKeyCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:connector:generatekey'
        description: 'Generates a random key for encrypting and decrypting connection passwords'
        schedulable: false
