services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterConnector\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Entity,Domain/Model,Exception,Extension.php}'

  Brotkrueml\JobRouterConnector\Utility\FileUtility:
    public: true

  Brotkrueml\JobRouterConnector\Controller\ConnectionTestController:
    tags: [ 'backend.controller' ]

  Brotkrueml\JobRouterConnector\Command\GenerateKeyCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:connector:generatekey'
        description: 'Generates a random key for encrypting and decrypting connection passwords'
        schedulable: false

  Brotkrueml\JobRouterConnector\Evaluation\Password:
    public: true
