name: Crowdin

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - '**.xlf'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  sync:
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Upload sources
        uses: crowdin/github-action@8868a33591d21088edfc398968173a3b98d51706 # v2.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: '.crowdin.yml'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          crowdin_branch_name: 'main'
          upload_sources: true
          upload_translations: false
          download_sources: false
          download_translations: false
