name: XLIFF

permissions: {}

on:
  push:
    branches-ignore:
      - l10n_main
    paths:
      - '**.xlf'
  pull_request:
    branches-ignore:
      - l10n_main
    paths:
      - '**.xlf'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  xliff-validation:
    name: XLIFF validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Install package
        run: |
          sudo apt-get -y install libxml2-utils
      - name: Validate XLIFF files
        run: |
          make lint-xlf
